name: Daily rollout daemonset K8s AKS

on:
  ## scheduled job at 5:30 UTC everyday
  schedule:
    - cron: '30 5 * * *'
  ## manual trigger
  # workflow_dispatch
  ## on push
  push:
    branches: [ main ]

permissions:
      id-token: write
      contents: read
jobs:
  deploy_sensor:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: restart_sensor
        run: |
             kubectl rollout restart daemonset -n falcon-system falcon-helm-falcon-sensor
